run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - govet
    - revive
    - staticcheck
    - unused
issues:
  exclude-rules:
    - path: "zz_generated.*\\.go"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0