version: "2"
linters:
  enable:
    - errcheck
    - govet
    - revive
    - staticcheck
    - unused
  exclusions:
    presets:
      - common-false-positives
    rules:
      - path: 'zz_generated.*\.go'
        linters:
          - ALL
      - path: '.*_test\.go'
        linters:
          - revive
        text: "dot-imports"