name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.3"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          security-checks: "vuln,config,secret"
          ignore-unfixed: true
          format: "table"
          exit-code: "1" # Fails the Workflow if high/crit issues are found
          severity: "HIGH,CRITICAL"

      - name: Build
        run: make build

      - name: Test
        run: make test


      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: ECR Login
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          IMAGE_TAG=v-$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.ECR_REPO_URL }}:${IMAGE_TAG} .
          docker push ${{ secrets.ECR_REPO_URL }}:${IMAGE_TAG}
      - name: Update manifests and push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          IMAGE_TAG=v-$(git rev-parse --short HEAD)
          sed -i "s|image: .*|image: ${{ secrets.ECR_REPO_URL }}:${IMAGE_TAG}|" deploy/install.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deploy/install.yaml
          git commit -m "chore: update operator image to ${IMAGE_TAG}"
          git push
